import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.loading': 'Loading...',
    'common.retry': 'Retry',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.notes': 'Notes',
    'common.tags': 'Tags',
    'common.amount': 'Amount',
    'common.date': 'Date',
    'common.type': 'Type',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.all': 'All',
    'common.noResults': 'No results found',
    'common.add': 'Add',
    
    // Dashboard
    'dashboard.welcomeBack': 'WELCOME BACK',
    'dashboard.owedToMe': 'Owed to Me',
    'dashboard.iOwe': 'I Owe',
    'dashboard.dailySalesManagement': 'Daily Sales Management',
    'dashboard.overdue': 'Overdue',
    'dashboard.highPriority': 'High Priority',
    'dashboard.bigBossManagement': 'Big Boss Management',
    'dashboard.staffManagement': 'Staff Management',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.viewAll': 'View All',
    'dashboard.noRecentActivity': 'No recent activity',
    'dashboard.filters.allActivity': 'All Activity',
    'dashboard.filters.dueSoon': 'Due Soon',
    'dashboard.filters.highAmount': 'High Amount',
    'dashboard.synced': 'Synced',
    'dashboard.pendingOperations': 'pending operation(s)',
    'dashboard.monthlyBalance': 'Monthly Balance',
    'dashboard.ledgerOwed': 'Ledger Owed',
    'dashboard.bigBossPaid': 'Big Boss Paid',
    'dashboard.balance': 'Balance',
    'dashboard.previousMonth': 'Previous Month',
    'dashboard.viewHistory': 'View History',
    'dashboard.currentMonth': 'Current Month',
    'dashboard.noMonthlyData': 'No data for this month',
    
    // Monthly Balance History
    'monthlyHistory.title': 'Monthly Balance History',
    'monthlyHistory.noHistory': 'No balance history yet',
    'monthlyHistory.year': 'Year',
    
    // Big Boss
    'bigboss.title': 'Big Boss Management',
    'bigboss.addBigBoss': 'Add Big Boss',
    'bigboss.createBigBoss': 'Create Big Boss',
    'bigboss.editBigBoss': 'Edit Big Boss',
    'bigboss.bigBossName': 'Big Boss Name',
    'bigboss.description': 'Description',
    'bigboss.optional': '(Optional)',
    'bigboss.totalPaid': 'Total Paid',
    'bigboss.noBigBosses': 'No Big Bosses yet',
    'bigboss.addFirstBigBoss': 'Add your first Big Boss to get started',
    'bigboss.bills': 'Bills',
    'bigboss.noBills': 'No bills yet',
    'bigboss.addBill': 'Add Bill',
    'bigboss.createBill': 'Create Bill',
    'bigboss.month': 'Month',
    'bigboss.year': 'Year',
    'bigboss.amount': 'Amount',
    'bigboss.attachment': 'Attachment',
    'bigboss.addAttachment': 'Add Attachment',
    'bigboss.removeAttachment': 'Remove Attachment',
    'bigboss.january': 'January',
    'bigboss.february': 'February',
    'bigboss.march': 'March',
    'bigboss.april': 'April',
    'bigboss.may': 'May',
    'bigboss.june': 'June',
    'bigboss.july': 'July',
    'bigboss.august': 'August',
    'bigboss.september': 'September',
    'bigboss.october': 'October',
    'bigboss.november': 'November',
    'bigboss.december': 'December',
    'bigboss.pay': 'Pay',
    'bigboss.paid': 'Paid',
    'bigboss.unpaid': 'Unpaid',
    'bigboss.payBill': 'Pay Bill',
    'bigboss.unpayBill': 'Unpay Bill',
    'bigboss.billPaid': 'Bill paid successfully',
    'bigboss.billUnpaid': 'Bill marked as unpaid',
    
    // Salary
    'salary.title': 'Salary Management',
    'salary.paySalary': 'Pay Salary',
    'salary.pay': 'Pay',
    'salary.allPayments': 'All Payments',
    'salary.mySalary': 'My Salary',
    'salary.staffSalary': 'Staff Salary',
    'salary.selectStaff': 'Select Staff',
    'salary.month': 'Month',
    'salary.year': 'Year',
    'salary.amount': 'Amount',
    'salary.paymentMethod': 'Payment Method',
    'salary.cash': 'Cash',
    'salary.bank': 'Bank',
    'salary.other': 'Other',
    'salary.note': 'Note',
    'salary.optional': '(Optional)',
    'salary.attachment': 'Attachment',
    'salary.addAttachment': 'Add Attachment',
    'salary.totalPaid': 'Total Paid',
    'salary.noPayments': 'No payments yet',
    'salary.paymentHistory': 'Payment History',
    'salary.summary': 'Summary',
    'salary.lastPayment': 'Last Payment',
    'salary.monthlySalary': 'Monthly Salary',
    'salary.paid': 'Paid',
    'salary.pending': 'Pending',
    'salary.paymentDetails': 'Payment Details',
    'salary.staffDetails': 'Staff Details',
    
    // Contacts
    'contacts.title': 'Contacts',
    'contacts.addContact': 'Add Contact',
    'contacts.searchPlaceholder': 'Search contacts...',
    'contacts.noContactsYet': 'No contacts yet',
    'contacts.noContactsMatchSearch': 'No contacts match your search',
    'contacts.addFirstContact': 'Add your first contact to get started',
    'contacts.contactProfile': 'Contact Profile',
    'contacts.call': 'Call',
    'contacts.message': 'Message',
    'contacts.netBalance': 'NET BALANCE',
    'contacts.owsMe': 'Owes Me',
    'contacts.iOwe': 'I Owe',
    'contacts.settleUp': 'Settle Up',
    'contacts.recordPayment': 'Record Payment',
    'contacts.newEntry': 'New Entry',
    'contacts.ledgers': 'Ledgers',
    'contacts.ledger': 'ledger',
    'contacts.ledgers_plural': 'ledgers',
    'contacts.moreTags': '+ more',
    
    // Ledger
    'ledger.title': 'Debt Ledger',
    'ledger.export': 'Export',
    'ledger.searchPlaceholder': 'Search debts...',
    'ledger.recentEntries': 'Recent Entries',
    'ledger.noLedgersFound': 'No ledgers found',
    'ledger.createFirstLedger': 'Create your first ledger to get started',
    'ledger.filter.all': 'All',
    'ledger.filter.lent': 'Lent',
    'ledger.filter.borrowed': 'Borrowed',
    'ledger.filter.overdue': 'Overdue',
    'ledger.filter.settled': 'Settled',
    'ledger.filterByDueDate': 'Filter by Due Date',
    'ledger.fromDate': 'From Date',
    'ledger.toDate': 'To Date',
    'ledger.clear': 'Clear',
    'ledger.apply': 'Apply',
    'ledger.tapToRetry': 'Tap to retry',
    'ledger.pdf.title': 'Ledger Report',
    'ledger.pdf.totalLent': 'Total Lent',
    'ledger.pdf.totalBorrowed': 'Total Borrowed',
    'ledger.pdf.netBalance': 'Net Balance',
    'ledger.pdf.balance': 'Balance',
    'ledger.pdf.dueDate': 'Due Date',
    'ledger.pdf.priority': 'Priority',
    'ledger.pdf.status': 'Status',
    'ledger.pdf.pending': 'Pending',
    'ledger.pdf.settled': 'Settled',
    'ledger.pdf.low': 'Low',
    'ledger.pdf.medium': 'Medium',
    'ledger.pdf.high': 'High',
    'ledger.pdf.generatedOn': 'Generated on',
    'ledger.pdf.totalRecords': 'Total Records',
    'ledger.pdf.total': 'Total',
    'ledger.pdf.detailTitle': 'Ledger Details',
    'ledger.pdf.initialAmount': 'Initial Amount',
    'ledger.pdf.totalAmount': 'Total Amount',
    'ledger.pdf.outstandingBalance': 'Outstanding Balance',
    'ledger.pdf.totalPaid': 'Total Paid',
    'ledger.pdf.paymentHistory': 'Payment History',
    'ledger.pdf.paymentDate': 'Date',
    'ledger.pdf.paymentType': 'Type',
    'ledger.pdf.paymentAmount': 'Amount',
    'ledger.pdf.paymentMethod': 'Method',
    'ledger.pdf.recordedBy': 'Recorded By',
    'ledger.pdf.payment': 'Payment',
    'ledger.pdf.adjustment': 'Adjustment',
    'ledger.pdf.refund': 'Refund',
    'ledger.pdf.cash': 'Cash',
    'ledger.pdf.bank': 'Bank',
    'ledger.pdf.other': 'Other',
    'ledger.pdf.noPayments': 'No payments recorded',
    'ledger.pdf.createdOn': 'Created on',
    'ledger.pdf.notes': 'Notes',
    'ledger.pdf.tags': 'Tags',
    
    // Staff
    'staff.title': 'Staff & Permissions',
    'staff.manageYourTeam': 'Manage Your Team',
    'staff.controlAccess': "Control who has access to your store's data and track their daily activities.",
    'staff.addNewStaffMember': 'Add New Staff Member',
    'staff.activeMembers': 'Active Members',
    'staff.inactivePending': 'Inactive / Pending',
    'staff.managePermissions': 'Manage Permissions',
    'staff.permissions.createLedger': 'Create Ledger',
    'staff.permissions.editLedger': 'Edit Ledger',
    'staff.permissions.deleteLedger': 'Delete Ledger',
    'staff.permissions.recordPayment': 'Record Payment',
    'staff.permissions.viewAllLedgers': 'View All Ledgers',
    'staff.permissions.manageStaff': 'Manage Staff',
    'staff.userCanAccess': 'User can access the app',
    'staff.userCannotAccess': 'User cannot access the app',
    'staff.saveChanges': 'Save Changes',
    'staff.createNewAccount': 'Create a new account for your team',
    'staff.fullName': 'Full Name',
    'staff.password': 'Password',
    'staff.role': 'Role',
    'staff.staff': 'Staff',
    'staff.admin': 'Admin',
    'staff.phoneOptional': 'Phone (Optional)',
    'staff.fillRequiredFields': 'Please fill in all required fields',
    'staff.staffAdded': 'Staff member added successfully',
    'staff.permissionRequired': 'Permission Required',
    'staff.noPermissionManageStaff': 'You do not have permission to manage staff.',
    
    // Modal
    'modal.newLedger': 'New Ledger',
    'modal.recordPayment': 'Record Payment',
    'modal.newContact': 'New Contact',
    'modal.createLedger': 'Create Ledger',
    'modal.confirmPayment': 'Confirm Payment',
    'modal.createContact': 'Create Contact',
    'modal.outstandingBalance': 'Outstanding Balance:',
    'modal.partialPaymentHelp': 'Record partial payment — outstanding will reduce automatically.',
    'modal.theyOweMe': 'They Owe Me',
    'modal.iOweThem': 'I Owe Them',
    'modal.enterNameOrCompany': 'Enter name or company',
    'modal.initialAmount': 'Initial Amount',
    'modal.notesOptional': 'Notes (Optional)',
    'modal.addNotes': 'Add notes...',
    'modal.paymentAmount': 'Payment Amount',
    'modal.method': 'Method',
    'modal.cash': 'Cash',
    'modal.bank': 'Bank',
    'modal.other': 'Other',
    'modal.noteOptional': 'Note (Optional)',
    'modal.addNotePayment': 'Add a note about this payment...',
    'modal.receiptOptional': 'Receipt (Optional)',
    'modal.attachReceipt': 'Attach receipt',
    'modal.receiptAttached': 'Receipt attached',
    'modal.ledgerFullySettled': 'This ledger is fully settled!',
    'modal.enterContactName': 'Enter contact name',
    'modal.enterEmail': 'Enter email address',
    'modal.enterPhone': 'Enter phone number',
    'modal.enterAddress': 'Enter address',
    'modal.addNotesContact': 'Add notes about this contact...',
    'modal.friendWorkFamily': 'friend, work, family (comma separated)',
    'modal.pleaseEnterName': 'Please enter a counterparty name',
    'modal.pleaseEnterValidAmount': 'Please enter a valid amount',
    'modal.paymentExceedBalance': 'Payment amount cannot exceed outstanding balance',
    'modal.pleaseEnterContactName': 'Please enter a contact name',
    'modal.ledgerCreated': 'Ledger created successfully',
    'modal.paymentRecorded': 'Payment recorded successfully!',
    'modal.newBalance': 'New balance:',
    'modal.contactCreated': 'Contact created successfully',
    'modal.idempotentResponse': 'This payment was already recorded (idempotent response)',
    
    // Ledger Detail
    'ledgerDetail.title': 'Ledger Details',
    'ledgerDetail.initial': 'Initial',
    'ledgerDetail.outstanding': 'Outstanding',
    'ledgerDetail.dueDate': 'Due Date',
    'ledgerDetail.na': 'N/A',
    'ledgerDetail.attachments': 'Attachments',
    'ledgerDetail.receipt': 'Receipt',
    'ledgerDetail.recordPayment': 'Record Payment',
    'ledgerDetail.addMoreDebt': 'Add More Debt',
    'ledgerDetail.paymentHistory': 'Payment History',
    'ledgerDetail.noPaymentsYet': 'No payments yet',
    'ledgerDetail.recordedBy': 'Recorded by',
    'ledgerDetail.outstandingStatus': 'Outstanding:',
    'ledgerDetail.editLedger': 'Edit Ledger',
    'ledgerDetail.priority': 'Priority',
    'ledgerDetail.low': 'Low',
    'ledgerDetail.medium': 'Medium',
    'ledgerDetail.high': 'High',
    'ledgerDetail.addTag': 'Add tag...',
    'ledgerDetail.addDebt': 'Add Debt',
    'ledgerDetail.enterName': 'Enter name',
    'ledgerDetail.enterAmount': 'Enter amount',
    'ledgerDetail.addNoteOptional': 'Add a note...',
    'ledgerDetail.theyOweMe': 'They owe me',
    'ledgerDetail.iOweThem': 'I owe them',
    'ledgerDetail.ledgerUpdated': 'Ledger updated successfully',
    'ledgerDetail.ledgerUpdatedError': 'Failed to update ledger',
    'ledgerDetail.deleteLedger': 'Delete Ledger',
    'ledgerDetail.deleteLedgerError': 'Failed to delete ledger',
    'ledgerDetail.enterValidAmount': 'Please enter a valid amount greater than 0',
    'ledgerDetail.ledgerDeleted': 'Ledger deleted',
    'ledgerDetail.deleteConfirm': 'Are you sure you want to delete this ledger? This action cannot be undone.',
    'ledgerDetail.debtAdded': 'Debt added successfully',
    'ledgerDetail.debtAddedError': 'Failed to add debt',
    'ledgerDetail.noActionsAvailable': 'No actions available',
    'ledgerDetail.ledgerNotFound': 'Ledger not found',
    'ledgerDetail.goBack': 'Go back',
    'ledgerDetail.overdueBy': 'Overdue by',
    'ledgerDetail.days': 'days',
    
    // Audit
    'audit.title': 'Audit Logs',
    'audit.noAuditLogs': 'No audit logs found',
    'audit.changes': 'Changes:',
    'audit.all': 'All',
    'audit.users': 'Users',
    'audit.ledgers': 'Ledgers',
    'audit.payments': 'Payments',
    
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.editProfile': 'Edit Profile',
    'settings.account': 'Account',
    'settings.changePassword': 'Change Password',
    'settings.about': 'About',
    'settings.version': 'Version',
    'settings.language': 'Language',
    'settings.english': 'English',
    'settings.bangla': 'Bangla',
    'settings.currency': 'Currency',
    'settings.bangladeshiTaka': 'Bangladeshi Taka',
    'settings.saudiRiyal': 'Saudi Riyal',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm Password',
    'settings.passwordsNotMatch': 'New passwords do not match',
    'settings.passwordMinLength': 'Password must be at least 6 characters',
    'settings.passwordChanged': 'Password changed successfully',
    'settings.profileUpdated': 'Profile updated successfully',
    'settings.addPhoto': 'Add Photo',
    'settings.company': 'Company',
    'settings.yourCompany': 'Your company',
    'settings.yourName': 'Your name',
    'settings.yourPhone': '+1 234 567 8900',
    'settings.enterCurrentPassword': 'Enter current password',
    'settings.enterNewPassword': 'Enter new password',
    'settings.confirmNewPassword': 'Confirm new password',
    'settings.change': 'Change',
    
    // Sales
    'sales.dashboard': 'Sales Management',
    'sales.addProduct': 'Add Product',
    'sales.viewProducts': 'View Products',
    'sales.addSale': 'Add Daily Sale',
    'sales.salesHistory': 'Sales History',
    'sales.products': 'Products',
    'sales.productName': 'Product Name',
    'sales.productPrice': 'Price',
    'sales.productImage': 'Product Image',
    'sales.enterProductName': 'Enter product name',
    'sales.enterPrice': 'Enter price',
    'sales.nameRequired': 'Product name is required',
    'sales.priceRequired': 'Valid price is required',
    'sales.editProduct': 'Edit Product',
    'sales.productNotFound': 'Product not found',
    'sales.searchProducts': 'Search products...',
    'sales.noProducts': 'No products yet',
    'sales.noProductsMatch': 'No products match your search',
    'sales.addFirstProduct': 'Add your first product to get started',
    'sales.deleteConfirmTitle': 'Delete Product',
    'sales.deleteConfirmMessage': 'Are you sure you want to delete',
    'sales.unsavedChanges': 'Unsaved Changes',
    'sales.discardChanges': 'Do you want to discard your changes?',
    'sales.discard': 'Discard',
    'sales.selectedItems': 'Selected Items',
    'sales.saveSale': 'Save Sale',
    'sales.saleSaved': 'Sale saved successfully!',
    'sales.success': 'Success',
    'sales.error': 'Error',
    'sales.noItemsInCart': 'No items in cart',
    'sales.unsavedCart': 'Unsaved Cart',
    'sales.discardCart': 'Do you want to discard this cart?',
    'sales.selectCustomer': 'Select Customer (Optional)',
    'sales.noCustomer': 'No Customer',
    'sales.noPreviousCustomers': 'No previous customers',
    'sales.noSales': 'No sales yet',
    'sales.noSalesDescription': 'Record your first sale to get started',
    'sales.deleteSaleConfirm': 'Are you sure you want to delete this sale?',
    'sales.saleDetails': 'Sale Details',
    'sales.saleNotFound': 'Sale not found',
    'sales.todaySales': "Today's Sales",
    'sales.filter': 'Filter',
    'sales.filterByDate': 'Filter by Date',
    'sales.fromDate': 'From Date',
    'sales.toDate': 'To Date',
    'sales.clearFilter': 'Clear',
    'sales.applyFilter': 'Apply',
    'sales.today': 'Today',
    'sales.yesterday': 'Yesterday',
    'sales.thisWeek': 'This Week',
    'sales.thisMonth': 'This Month',
    'sales.allTime': 'All Time',
    'sales.exportPdf': 'Export PDF',
    'sales.pdf.title': 'Sales Report',
    'sales.pdf.dateRange': 'Date Range',
    'sales.pdf.totalSales': 'Total Sales',
    'sales.pdf.transactions': 'Transactions',
    'sales.pdf.paidSales': 'Paid Sales',
    'sales.pdf.creditSales': 'Credit Sales',
    'sales.pdf.generatedOn': 'Generated on',
    'sales.pdf.items': 'Items',
    'sales.pdf.quantity': 'Qty',
    'sales.pdf.price': 'Price',
    'sales.pdf.subtotal': 'Subtotal',
    'sales.pdf.paymentStatus': 'Status',
    'sales.pdf.paid': 'Paid',
    'sales.pdf.notPaid': 'Not Paid',
    'sales.pdf.customer': 'Customer',
    'sales.pdf.noSalesFound': 'No sales found for the selected date range',
    'sales.pdf.allTime': 'All Time',
    'sales.pdf.cash': 'Cash',
    'sales.pdf.card': 'Card',
    'sales.paid': 'Paid',
    'sales.notPaid': 'Not Paid',
    'sales.paymentMethod': 'Payment Method',
    'sales.cash': 'Cash',
    'sales.payment': 'Payment',
    'sales.paymentReceived': 'Payment Received',
    'sales.card': 'Card',
    'sales.close': 'Close',
    'sales.printPdf': 'Print PDF',
  },
  bn: {
    // Common
    'common.cancel': 'বাতিল',
    'common.save': 'সংরক্ষণ',
    'common.delete': 'মুছুন',
    'common.edit': 'সম্পাদনা',
    'common.error': 'ত্রুটি',
    'common.success': 'সফল',
    'common.loading': 'লোড হচ্ছে...',
    'common.retry': 'আবার চেষ্টা',
    'common.close': 'বন্ধ',
    'common.search': 'অনুসন্ধান',
    'common.name': 'নাম',
    'common.email': 'ইমেইল',
    'common.phone': 'ফোন',
    'common.address': 'ঠিকানা',
    'common.notes': 'নোট',
    'common.tags': 'ট্যাগ',
    'common.amount': 'পরিমাণ',
    'common.date': 'তারিখ',
    'common.type': 'ধরন',
    'common.active': 'সক্রিয়',
    'common.inactive': 'নিষ্ক্রিয়',
    'common.all': 'সব',
    'common.noResults': 'কোনো ফলাফল পাওয়া যায়নি',
    'common.add': 'যোগ করুন',
    
    // Dashboard
    'dashboard.welcomeBack': 'স্বাগতম',
    'dashboard.owedToMe': 'আমাকে দেওয়া বাকি',
    'dashboard.iOwe': 'আমি দেই',
    'dashboard.dailySalesManagement': 'দৈনিক বিক্রয় ব্যবস্থাপনা',
    'dashboard.overdue': 'বকেয়া',
    'dashboard.highPriority': 'উচ্চ অগ্রাধিকার',
    'dashboard.recentActivity': 'সাম্প্রতিক কার্যক্রম',
    'dashboard.viewAll': 'সব দেখুন',
    'dashboard.noRecentActivity': 'কোনো সাম্প্রতিক কার্যক্রম নেই',
    'dashboard.filters.allActivity': 'সব কার্যক্রম',
    'dashboard.filters.dueSoon': 'শীঘ্রই দেওয়ার তারিখ',
    'dashboard.filters.highAmount': 'উচ্চ পরিমাণ',
    'dashboard.synced': 'সিঙ্ক হয়েছে',
    'dashboard.pendingOperations': 'টি মেয়াদী অপারেশন',
    'dashboard.monthlyBalance': 'মাসিক ব্যালেন্স',
    'dashboard.ledgerOwed': 'লেজারে পাওনা',
    'dashboard.bigBossPaid': 'বিগ বস পেমেন্ট',
    'dashboard.balance': 'ব্যালেন্স',
    'dashboard.previousMonth': 'গত মাস',
    'dashboard.viewHistory': 'ইতিহাস দেখুন',
    'dashboard.currentMonth': 'বর্তমান মাস',
    'dashboard.noMonthlyData': 'এই মাসে কোনো তথ্য নেই',
    
    // Monthly Balance History
    'monthlyHistory.title': 'মাসিক ব্যালেন্স ইতিহাস',
    'monthlyHistory.noHistory': 'কোনো ব্যালেন্স ইতিহাস নেই',
    'monthlyHistory.year': 'বছর',
    
    // Contacts
    'contacts.title': 'যোগাযোগ',
    'contacts.addContact': 'যোগাযোগ যোগ করুন',
    'contacts.searchPlaceholder': 'যোগাযোগ অনুসন্ধান...',
    'contacts.noContactsYet': 'এখনও কোনো যোগাযোগ নেই',
    'contacts.noContactsMatchSearch': 'আপনার অনুসন্ধানের সাথে কোনো যোগাযোগ মেলেনি',
    'contacts.addFirstContact': 'শুরু করতে আপনার প্রথম যোগাযোগ যোগ করুন',
    'contacts.contactProfile': 'যোগাযোগ প্রোফাইল',
    'contacts.call': 'কল',
    'contacts.message': 'মেসেজ',
    'contacts.netBalance': 'মোট ব্যালেন্স',
    'contacts.owsMe': 'আমাকে দেয়',
    'contacts.iOwe': 'আমি দেই',
    'contacts.settleUp': 'বিল পরিশোধ',
    'contacts.recordPayment': 'পেমেন্ট রেকর্ড',
    'contacts.newEntry': 'নতুন এন্ট্রি',
    'contacts.ledgers': 'লেজার',
    'contacts.ledger': 'লেজার',
    'contacts.ledgers_plural': 'লেজার',
    'contacts.moreTags': '+ আরও',
    
    // Ledger
    'ledger.title': 'ঋণ লেজার',
    'ledger.export': 'রপ্তানি',
    'ledger.searchPlaceholder': 'ঋণ অনুসন্ধান...',
    'ledger.recentEntries': 'সাম্প্রতিক এন্ট্রি',
    'ledger.noLedgersFound': 'কোনো লেজার পাওয়া যায়নি',
    'ledger.createFirstLedger': 'শুরু করতে আপনার প্রথম লেজার তৈরি করুন',
    'ledger.filter.all': 'সব',
    'ledger.filter.lent': 'দেওয়া',
    'ledger.filter.borrowed': 'নেওয়া',
    'ledger.filter.overdue': 'বকেয়া',
    'ledger.filter.settled': 'পরিশোধিত',
    'ledger.filterByDueDate': 'দেওয়ার তারিখ অনুযায়ী ফিল্টার',
    'ledger.fromDate': 'শুরু তারিখ',
    'ledger.toDate': 'শেষ তারিখ',
    'ledger.clear': 'মুছুন',
    'ledger.apply': 'প্রয়োগ',
    'ledger.tapToRetry': 'আবার চেষ্টা করতে ট্যাপ করুন',
    'ledger.pdf.title': 'ঋণ রিপোর্ট',
    'ledger.pdf.totalLent': 'মোট নেওয়া',
    'ledger.pdf.totalBorrowed': 'মোট দেওয়া',
    'ledger.pdf.netBalance': 'নেট ব্যালান্স',
    'ledger.pdf.balance': 'ব্যালান্স',
    'ledger.pdf.dueDate': 'দেওয়ার তারিখ',
    'ledger.pdf.priority': 'অগ্রাধিকার',
    'ledger.pdf.status': 'স্ট্যাটাস',
    'ledger.pdf.pending': 'মুলতুবি',
    'ledger.pdf.settled': 'পরিশোধিত',
    'ledger.pdf.low': 'কম',
    'ledger.pdf.medium': 'মাঝারি',
    'ledger.pdf.high': 'উচ্চ',
    'ledger.pdf.generatedOn': 'তৈরি হয়েছে',
    'ledger.pdf.totalRecords': 'মোট রেকর্ড',
    'ledger.pdf.total': 'মোট',
    'ledger.pdf.detailTitle': 'ঋণ বিবরণ',
    'ledger.pdf.initialAmount': 'প্রাথমিক পরিমাণ',
    'ledger.pdf.totalAmount': 'মোট পরিমাণ',
    'ledger.pdf.outstandingBalance': 'বকেয়া ব্যালান্স',
    'ledger.pdf.totalPaid': 'মোট পরিশোধিত',
    'ledger.pdf.paymentHistory': 'পেমেন্ট ইতিহাস',
    'ledger.pdf.paymentDate': 'তারিখ',
    'ledger.pdf.paymentType': 'ধরন',
    'ledger.pdf.paymentAmount': 'পরিমাণ',
    'ledger.pdf.paymentMethod': 'পদ্ধতি',
    'ledger.pdf.recordedBy': 'রেকর্ড করেছেন',
    'ledger.pdf.payment': 'পেমেন্ট',
    'ledger.pdf.adjustment': 'সমন্বয়',
    'ledger.pdf.refund': 'ফেরত',
    'ledger.pdf.cash': 'নগদ',
    'ledger.pdf.bank': 'ব্যাংক',
    'ledger.pdf.other': 'অন্যান্য',
    'ledger.pdf.noPayments': 'কোনো পেমেন্ট নেই',
    'ledger.pdf.createdOn': 'তৈরি হয়েছে',
    'ledger.pdf.notes': 'নোট',
    'ledger.pdf.tags': 'ট্যাগ',
    
    // Staff
    'staff.title': 'স্টাফ ও অনুমতি',
    'staff.manageYourTeam': 'আপনার টিম পরিচালনা করুন',
    'staff.controlAccess': 'আপনার স্টোরের ডেটায় কার অ্যাক্সেস আছে তা নিয়ন্ত্রণ করুন এবং তাদের দৈনিক কার্যক্রম ট্র্যাক করুন।',
    'staff.addNewStaffMember': 'নতুন স্টাফ সদস্য যোগ করুন',
    'staff.activeMembers': 'সক্রিয় সদস্য',
    'staff.inactivePending': 'নিষ্ক্রিয় / মুলতুবি',
    'staff.managePermissions': 'অনুমতি পরিচালনা',
    'staff.permissions.createLedger': 'লেজার তৈরি',
    'staff.permissions.editLedger': 'লেজার সম্পাদনা',
    'staff.permissions.deleteLedger': 'লেজার মুছুন',
    'staff.permissions.recordPayment': 'পেমেন্ট রেকর্ড',
    'staff.permissions.viewAllLedgers': 'সব লেজার দেখুন',
    'staff.permissions.manageStaff': 'স্টাফ পরিচালনা',
    'staff.userCanAccess': 'ব্যবহারকারী অ্যাপ অ্যাক্সেস করতে পারে',
    'staff.userCannotAccess': 'ব্যবহারকারী অ্যাপ অ্যাক্সেস করতে পারে না',
    'staff.saveChanges': 'পরিবর্তন সংরক্ষণ',
    'staff.createNewAccount': 'আপনার টিমের জন্য একটি নতুন অ্যাকাউন্ট তৈরি করুন',
    'staff.fullName': 'পুরো নাম',
    'staff.password': 'পাসওয়ার্ড',
    'staff.role': 'ভূমিকা',
    'staff.staff': 'স্টাফ',
    'staff.admin': 'অ্যাডমিন',
    'staff.phoneOptional': 'ফোন (ঐচ্ছিক)',
    'staff.fillRequiredFields': 'অনুগ্রহ করে সব প্রয়োজনীয় ফিল্ড পূরণ করুন',
    'staff.staffAdded': 'স্টাফ সদস্য সফলভাবে যোগ করা হয়েছে',
    'staff.permissionRequired': 'অনুমতি প্রয়োজন',
    'staff.noPermissionManageStaff': 'স্টাফ পরিচালনা করার অনুমতি আপনার নেই।',
    
    // Modal
    'modal.newLedger': 'নতুন লেজার',
    'modal.recordPayment': 'পেমেন্ট রেকর্ড',
    'modal.newContact': 'নতুন যোগাযোগ',
    'modal.createLedger': 'লেজার তৈরি',
    'modal.confirmPayment': 'পেমেন্ট নিশ্চিত',
    'modal.createContact': 'যোগাযোগ তৈরি',
    'modal.outstandingBalance': 'বকেয়া ব্যালেন্স:',
    'modal.partialPaymentHelp': 'আংশিক পেমেন্ট রেকর্ড করুন — বকেয়া স্বয়ংক্রিয়ভাবে কমে যাবে।',
    'modal.theyOweMe': 'ওরা আমাকে দেয়',
    'modal.iOweThem': 'আমি ওদের দেই',
    'modal.enterNameOrCompany': 'নাম বা কোম্পানি লিখুন',
    'modal.initialAmount': 'প্রাথমিক পরিমাণ',
    'modal.notesOptional': 'নোট (ঐচ্ছিক)',
    'modal.addNotes': 'নোট যোগ করুন...',
    'modal.paymentAmount': 'পেমেন্ট পরিমাণ',
    'modal.method': 'পদ্ধতি',
    'modal.cash': 'ক্যাশ',
    'modal.bank': 'ব্যাংক',
    'modal.other': 'অন্যান্য',
    'modal.noteOptional': 'নোট (ঐচ্ছিক)',
    'modal.addNotePayment': 'এই পেমেন্ট সম্পর্কে একটি নোট যোগ করুন...',
    'modal.receiptOptional': 'রসিদ (ঐচ্ছিক)',
    'modal.attachReceipt': 'রসিদ সংযুক্ত করুন',
    'modal.receiptAttached': 'রসিদ সংযুক্ত',
    'modal.ledgerFullySettled': 'এই লেজার সম্পূর্ণ পরিশোধিত!',
    'modal.enterContactName': 'যোগাযোগের নাম লিখুন',
    'modal.enterEmail': 'ইমেইল ঠিকানা লিখুন',
    'modal.enterPhone': 'ফোন নম্বর লিখুন',
    'modal.enterAddress': 'ঠিকানা লিখুন',
    'modal.addNotesContact': 'এই যোগাযোগ সম্পর্কে নোট যোগ করুন...',
    'modal.friendWorkFamily': 'বন্ধু, কাজ, পরিবার (কমা দিয়ে আলাদা)',
    'modal.pleaseEnterName': 'অনুগ্রহ করে কাউন্টারপার্টির নাম লিখুন',
    'modal.pleaseEnterValidAmount': 'অনুগ্রহ করে একটি বৈধ পরিমাণ লিখুন',
    'modal.paymentExceedBalance': 'পেমেন্ট পরিমাণ বকেয়া ব্যালেন্স অতিক্রম করতে পারে না',
    'modal.pleaseEnterContactName': 'অনুগ্রহ করে যোগাযোগের নাম লিখুন',
    'modal.ledgerCreated': 'লেজার সফলভাবে তৈরি হয়েছে',
    'modal.paymentRecorded': 'পেমেন্ট সফলভাবে রেকর্ড হয়েছে!',
    'modal.newBalance': 'নতুন ব্যালেন্স:',
    'modal.contactCreated': 'যোগাযোগ সফলভাবে তৈরি হয়েছে',
    'modal.idempotentResponse': 'এই পেমেন্ট ইতিমধ্যে রেকর্ড হয়েছে (idempotent response)',
    
    // Ledger Detail
    'ledgerDetail.title': 'লেজার বিবরণ',
    'ledgerDetail.initial': 'প্রাথমিক',
    'ledgerDetail.outstanding': 'বকেয়া',
    'ledgerDetail.dueDate': 'দেওয়ার তারিখ',
    'ledgerDetail.na': 'এন/এ',
    'ledgerDetail.attachments': 'সংযুক্তি',
    'ledgerDetail.receipt': 'রসিদ',
    'ledgerDetail.recordPayment': 'পেমেন্ট রেকর্ড',
    'ledgerDetail.addMoreDebt': 'আরও ঋণ যোগ',
    'ledgerDetail.paymentHistory': 'পেমেন্ট ইতিহাস',
    'ledgerDetail.noPaymentsYet': 'এখনও কোনো পেমেন্ট নেই',
    'ledgerDetail.recordedBy': 'রেকর্ড করেছেন',
    'ledgerDetail.outstandingStatus': 'বকেয়া:',
    'ledgerDetail.editLedger': 'লেজার সম্পাদনা',
    'ledgerDetail.priority': 'অগ্রাধিকার',
    'ledgerDetail.low': 'কম',
    'ledgerDetail.medium': 'মাঝারি',
    'ledgerDetail.high': 'উচ্চ',
    'ledgerDetail.addTag': 'ট্যাগ যোগ...',
    'ledgerDetail.addDebt': 'ঋণ যোগ',
    'ledgerDetail.enterName': 'নাম লিখুন',
    'ledgerDetail.enterAmount': 'পরিমাণ লিখুন',
    'ledgerDetail.addNoteOptional': 'একটি নোট যোগ করুন...',
    'ledgerDetail.theyOweMe': 'ওরা আমাকে দেয়',
    'ledgerDetail.iOweThem': 'আমি ওদের দেই',
    'ledgerDetail.ledgerUpdated': 'লেজার সফলভাবে আপডেট হয়েছে',
    'ledgerDetail.ledgerUpdatedError': 'লেজার আপডেট করতে ব্যর্থ',
    'ledgerDetail.deleteLedger': 'লেজার মুছুন',
    'ledgerDetail.deleteLedgerError': 'লেজার মুছতে ব্যর্থ',
    'ledgerDetail.enterValidAmount': 'অনুগ্রহ করে ০ এর বেশি একটি বৈধ পরিমাণ লিখুন',
    'ledgerDetail.ledgerDeleted': 'লেজার মুছে ফেলা হয়েছে',
    'ledgerDetail.deleteConfirm': 'আপনি কি নিশ্চিত যে আপনি এই লেজার মুছতে চান? এই কাজটি পূরণ করা যাবে না।',
    'ledgerDetail.debtAdded': 'ঋণ সফলভাবে যোগ করা হয়েছে',
    'ledgerDetail.debtAddedError': 'ঋণ যোগ করতে ব্যর্থ',
    'ledgerDetail.noActionsAvailable': 'কোনো অ্যাকশন উপলব্ধ নেই',
    'ledgerDetail.ledgerNotFound': 'লেজার পাওয়া যায়নি',
    'ledgerDetail.goBack': 'ফিরে যান',
    'ledgerDetail.overdueBy': 'বকেয়া',
    'ledgerDetail.days': 'দিন',
    
    // Audit
    'audit.title': 'অডিট লগ',
    'audit.noAuditLogs': 'কোনো অডিট লগ পাওয়া যায়নি',
    'audit.changes': 'পরিবর্তন:',
    'audit.all': 'সব',
    'audit.users': 'ব্যবহারকারী',
    'audit.ledgers': 'লেজার',
    'audit.payments': 'পেমেন্ট',
    
    // Settings
    'settings.title': 'সেটিংস',
    'settings.profile': 'প্রোফাইল',
    'settings.editProfile': 'প্রোফাইল সম্পাদনা',
    'settings.account': 'অ্যাকাউন্ট',
    'settings.changePassword': 'পাসওয়ার্ড পরিবর্তন',
    'settings.about': 'সম্পর্কে',
    'settings.version': 'ভার্সন',
    'settings.language': 'ভাষা',
    'settings.english': 'ইংরেজি',
    'settings.bangla': 'বাংলা',
    'settings.currency': 'মুদ্রা',
    'settings.bangladeshiTaka': 'বাংলাদেশী টাকা',
    'settings.saudiRiyal': 'সৌদি রিয়াল',
    'settings.currentPassword': 'বর্তমান পাসওয়ার্ড',
    'settings.newPassword': 'নতুন পাসওয়ার্ড',
    'settings.confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
    'settings.passwordsNotMatch': 'নতুন পাসওয়ার্ড মিলছে না',
    'settings.passwordMinLength': 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে',
    'settings.passwordChanged': 'পাসওয়ার্ড সফলভাবে পরিবর্তন হয়েছে',
    'settings.profileUpdated': 'প্রোফাইল সফলভাবে আপডেট হয়েছে',
    'settings.addPhoto': 'ফোটো যোগ করুন',
    'settings.company': 'কোম্পানি',
    'settings.yourCompany': 'আপনার কোম্পানি',
    'settings.yourName': 'আপনার নাম',
    'settings.yourPhone': '+1 234 567 8900',
    'settings.enterCurrentPassword': 'বর্তমান পাসওয়ার্ড লিখুন',
    'settings.enterNewPassword': 'নতুন পাসওয়ার্ড লিখুন',
    'settings.confirmNewPassword': 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
    'settings.change': 'পরিবর্তন',
    
    // Sales
    'sales.dashboard': 'বিক্রয় ব্যবস্থাপনা',
    'sales.addProduct': 'পণ্য যোগ করুন',
    'sales.viewProducts': 'পণ্য দেখুন',
    'sales.addSale': 'দৈনিক বিক্রয়',
    'sales.salesHistory': 'বিক্রয় ইতিহাস',
    'sales.products': 'পণ্য',
    'sales.productName': 'পণ্যের নাম',
    'sales.productPrice': 'মূল্য',
    'sales.productImage': 'পণ্যের ছবি',
    'sales.enterProductName': 'পণ্যের নাম লিখুন',
    'sales.enterPrice': 'মূল্য লিখুন',
    'sales.nameRequired': 'পণ্যের নাম প্রয়োজন',
    'sales.priceRequired': 'বৈধ মূল্য প্রয়োজন',
    'sales.editProduct': 'পণ্য সম্পাদনা',
    'sales.productNotFound': 'পণ্য পাওয়া যায়নি',
    'sales.searchProducts': 'পণ্য অনুসন্ধান...',
    'sales.noProducts': 'কোনো পণ্য নেই',
    'sales.noProductsMatch': 'কোনো পণ্য মেলেনি',
    'sales.addFirstProduct': 'প্রথম পণ্য যোগ করুন',
    'sales.deleteConfirmTitle': 'পণ্য মুছুন',
    'sales.deleteConfirmMessage': 'আপনি কি এই পণ্য মুছতে চান',
    'sales.unsavedChanges': 'সংরক্ষিত পরিবর্তন',
    'sales.discardChanges': 'আপনি কি পরিবর্তন বাতিল করতে চান?',
    'sales.discard': 'বাতিল',
    'sales.selectedItems': 'নির্বাচিত আইটেম',
    'sales.saveSale': 'বিক্রয় সংরক্ষণ',
    'sales.saleSaved': 'বিক্রয় সফলভাবে সংরক্ষিত!',
    'sales.success': 'সফল',
    'sales.error': 'ত্রুটি',
    'sales.noItemsInCart': 'কার্টে কোনো আইটেম নেই',
    'sales.unsavedCart': 'সংরক্ষিত কার্ট',
    'sales.discardCart': 'আপনি কি এই কার্ট বাতিল করতে চান?',
    'sales.selectCustomer': 'গ্রাহক নির্বাচন (ঐচ্ছিক)',
    'sales.noCustomer': 'কোনো গ্রাহক নেই',
    'sales.noPreviousCustomers': 'কোনো পূর্ববর্তী গ্রাহক নেই',
    'sales.noSales': 'কোনো বিক্রয় নেই',
    'sales.noSalesDescription': 'প্রথম বিক্রয় রেকর্ড করুন',
    'sales.deleteSaleConfirm': 'আপনি কি এই বিক্রয় মুছতে চান?',
    'sales.saleDetails': 'বিক্রয় বিবরণ',
    'sales.saleNotFound': 'বিক্রয় পাওয়া যায়নি',
    'sales.todaySales': 'আজকের বিক্রয়',
    'sales.filter': 'ফিল্টার',
    'sales.filterByDate': 'তারিখ অনুযায়ী ফিল্টার',
    'sales.fromDate': 'শুরু তারিখ',
    'sales.toDate': 'শেষ তারিখ',
    'sales.clearFilter': 'মুছুন',
    'sales.applyFilter': 'প্রয়োগ',
    'sales.today': 'আজ',
    'sales.yesterday': 'গতকাল',
    'sales.thisWeek': 'এই সপ্তাহ',
    'sales.thisMonth': 'এই মাস',
    'sales.allTime': 'সব সময়',
    'sales.exportPdf': 'পিডিএফ রপ্তানি',
    'sales.pdf.title': 'বিক্রয় রিপোর্ট',
    'sales.pdf.dateRange': 'তারিখ সীমা',
    'sales.pdf.totalSales': 'মোট বিক্রয়',
    'sales.pdf.transactions': 'লেনদেন',
    'sales.pdf.paidSales': 'নগদ বিক্রয়',
    'sales.pdf.creditSales': 'ক্রেডিট বিক্রয়',
    'sales.pdf.generatedOn': 'তৈরি হয়েছে',
    'sales.pdf.items': 'আইটেম',
    'sales.pdf.quantity': 'পরিমাণ',
    'sales.pdf.price': 'মূল্য',
    'sales.pdf.subtotal': 'উপমোট',
    'sales.pdf.paymentStatus': 'স্ট্যাটাস',
    'sales.pdf.paid': 'পরিশোধিত',
    'sales.pdf.notPaid': 'বকেয়া',
    'sales.pdf.customer': 'গ্রাহক',
    'sales.pdf.noSalesFound': 'নির্বাচিত তারিখ সীমায় কোনো বিক্রয় পাওয়া যায়নি',
    'sales.pdf.allTime': 'সব সময়',
    'sales.pdf.cash': 'নগদ',
    'sales.pdf.card': 'কার্ড',
    'sales.paid': 'পরিশোধিত',
    'sales.notPaid': 'বকেয়া',
    'sales.paymentMethod': 'পেমেন্ট পদ্ধতি',
    'sales.cash': 'নগদ',
    'sales.card': 'কার্ড',
    'sales.payment': 'পেমেন্ট',
    'sales.paymentReceived': 'পেমেন্ট গৃহীত',
    'sales.close': 'বন্ধ করুন',
    'sales.printPdf': 'পিডিএফ প্রিন্ট করুন',
  },
};

const LANGUAGE_STORAGE_KEY = '@app_language';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  const [isReady, setIsReady] = useState(false);

  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const AsyncStorage = require('@react-native-async-storage/async-storage').default;
        const savedLang = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
        if (savedLang === 'en' || savedLang === 'bn') {
          setLanguageState(savedLang);
        }
      } catch (error) {
        console.log('LanguageContext: AsyncStorage not available yet');
      } finally {
        setIsReady(true);
      }
    };
    
    loadLanguage();
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      const AsyncStorage = require('@react-native-async-storage/async-storage').default;
      AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, lang).catch(() => {});
    } catch (error) {
      console.log('LanguageContext: AsyncStorage not available');
    }
  };

  const t = (key: string): string => {
    return TRANSLATIONS[language][key] || key;
  };

  if (!isReady) {
    return (
      <LanguageContext.Provider value={{ language: 'en', setLanguage: () => {}, t: (key: string) => TRANSLATIONS['en'][key] || key }}>
        {children}
      </LanguageContext.Provider>
    );
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
